SELECT 	GATEWAY_ID, DEVICE_ADDRESS, END_POINT, COLLECTED_DATE, COLLECTED_TIME, QUALITY, ONOFF, MAX(ENERGY)-MIN(ENERGY) AS ENERGY, 
			ENERGY_DIFF, count(APPLIANCE_STATUS) AS APPLIANCE_STATUS, CREATE_DATE
FROM AH_USE_LOG_BYMINUTE_LABLED
WHERE 1=1
	AND GATEWAY_ID = 'ep17470141'
	AND DEVICE_ADDRESS = '00158D000151B1F9'
GROUP BY APPLIANCE_STATUS